Update ureq used by nodejs-engine to match libherokubuildpack
To fix:

```
 error[E0277]: the trait bound `DownloadError: From<Box<ureq::Error>>` is not satisfied
   --> buildpacks/nodejs-engine/src/errors.rs:364:64
    |
364 |         Box::new(ureq::get("broken/ url").call().unwrap_err()).into()
    |                                                                ^^^^ the trait `From<Box<ureq::Error>>` is not implemented for `DownloadError`
    |
    = help: the following other types implement trait `From<T>`:
              `DownloadError` implements `From<Box<ureq::error::Error>>`
              `DownloadError` implements `From<std::io::Error>`
    = note: required for `Box<ureq::Error>` to implement `Into<DownloadError>`
```

I've left the other ureq usages as is for now, since they will require further
changes and already have a separate major-version Dependabot PR open:
https://github.com/heroku/buildpacks-nodejs/pull/1059