Fix breakage now that `fun_run` is its own crate
Fixes:

```
error[E0432]: unresolved import `commons::fun_run`
 --> buildpacks/nodejs-npm-install/src/errors.rs:3:14
  |
3 | use commons::fun_run::CmdError;
  |              ^^^^^^^ could not find `fun_run` in `commons`
```
etc

Which is due to:
https://github.com/heroku/buildpacks-ruby/pull/232