Bump the rust-dependencies group across 1 directory with 9 updates (#1063)
* Bump the rust-dependencies group across 1 directory with 9 updates

Bumps the rust-dependencies group with 9 updates in the / directory:

| Package | From | To |
| --- | --- | --- |
| [indoc](https://github.com/dtolnay/indoc) | `2.0.5` | `2.0.6` |
| [libcnb](https://github.com/heroku/libcnb.rs) | `0.27.0` | `0.28.0` |
| [libherokubuildpack](https://github.com/heroku/libcnb.rs) | `0.27.0` | `0.28.0` |
| [serde](https://github.com/serde-rs/serde) | `1.0.218` | `1.0.219` |
| [tempfile](https://github.com/Stebalien/tempfile) | `3.17.1` | `3.19.1` |
| [libcnb-test](https://github.com/heroku/libcnb.rs) | `0.27.0` | `0.28.0` |
| [opentelemetry](https://github.com/open-telemetry/opentelemetry-rust) | `0.28.0` | `0.29.0` |
| [bon](https://github.com/elastio/bon) | `3.3.2` | `3.5.1` |
| [libcnb-data](https://github.com/heroku/libcnb.rs) | `0.27.0` | `0.28.0` |



Updates `indoc` from 2.0.5 to 2.0.6
- [Release notes](https://github.com/dtolnay/indoc/releases)
- [Commits](https://github.com/dtolnay/indoc/compare/2.0.5...2.0.6)

Updates `libcnb` from 0.27.0 to 0.28.0
- [Release notes](https://github.com/heroku/libcnb.rs/releases)
- [Changelog](https://github.com/heroku/libcnb.rs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/heroku/libcnb.rs/compare/v0.27.0...v0.28.0)

Updates `libherokubuildpack` from 0.27.0 to 0.28.0
- [Release notes](https://github.com/heroku/libcnb.rs/releases)
- [Changelog](https://github.com/heroku/libcnb.rs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/heroku/libcnb.rs/compare/v0.27.0...v0.28.0)

Updates `serde` from 1.0.218 to 1.0.219
- [Release notes](https://github.com/serde-rs/serde/releases)
- [Commits](https://github.com/serde-rs/serde/compare/v1.0.218...v1.0.219)

Updates `tempfile` from 3.17.1 to 3.19.1
- [Changelog](https://github.com/Stebalien/tempfile/blob/master/CHANGELOG.md)
- [Commits](https://github.com/Stebalien/tempfile/compare/v3.17.1...v3.19.1)

Updates `libcnb-test` from 0.27.0 to 0.28.0
- [Release notes](https://github.com/heroku/libcnb.rs/releases)
- [Changelog](https://github.com/heroku/libcnb.rs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/heroku/libcnb.rs/compare/v0.27.0...v0.28.0)

Updates `opentelemetry` from 0.28.0 to 0.29.0
- [Release notes](https://github.com/open-telemetry/opentelemetry-rust/releases)
- [Commits](https://github.com/open-telemetry/opentelemetry-rust/compare/opentelemetry-0.28.0...opentelemetry-0.29.0)

Updates `bon` from 3.3.2 to 3.5.1
- [Release notes](https://github.com/elastio/bon/releases)
- [Changelog](https://github.com/elastio/bon/blob/master/release-plz.toml)
- [Commits](https://github.com/elastio/bon/compare/v3.3.2...v3.5.1)

Updates `libcnb-data` from 0.27.0 to 0.28.0
- [Release notes](https://github.com/heroku/libcnb.rs/releases)
- [Changelog](https://github.com/heroku/libcnb.rs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/heroku/libcnb.rs/compare/v0.27.0...v0.28.0)

---
updated-dependencies:
- dependency-name: indoc
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: libcnb
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: libherokubuildpack
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: serde
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: tempfile
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: libcnb-test
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: opentelemetry
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: bon
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: libcnb-data
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update to libcnb 0.28.1 and refresh lockfile

* Downgrade opentelemetry to 0.28

So it matches the libcnb version.

* Update ureq used by nodejs-engine to match libherokubuildpack

To fix:

```
 error[E0277]: the trait bound `DownloadError: From<Box<ureq::Error>>` is not satisfied
   --> buildpacks/nodejs-engine/src/errors.rs:364:64
    |
364 |         Box::new(ureq::get("broken/ url").call().unwrap_err()).into()
    |                                                                ^^^^ the trait `From<Box<ureq::Error>>` is not implemented for `DownloadError`
    |
    = help: the following other types implement trait `From<T>`:
              `DownloadError` implements `From<Box<ureq::error::Error>>`
              `DownloadError` implements `From<std::io::Error>`
    = note: required for `Box<ureq::Error>` to implement `Into<DownloadError>`
```

I've left the other ureq usages as is for now, since they will require further
changes and already have a separate major-version Dependabot PR open:
https://github.com/heroku/buildpacks-nodejs/pull/1059

* Remove unused ureq dependencies from other crates

I presume these are leftover from test helpers being moved
to the shared test utils crate.

* Fix lint errors with the newly released Rust 1.86

Fixes the errors seen here:
https://github.com/heroku/buildpacks-nodejs/actions/runs/14242580302/job/39915727106?pr=1063#step:5:453

* Update insta snapshot

Due to libherokubuildpack upgrading to ureq 3, which uses
the `http` crate internally now.

The snapshot was updated using the `cargo insta` CLI.

Fixes this snapshot error:
https://github.com/heroku/buildpacks-nodejs/actions/runs/14242580302/job/39915726551?pr=1063#step:5:496

* Upgrade remaining `ureq` usages

---------

Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: Colin Casey <casey.colin@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>
Co-authored-by: Colin Casey <casey.colin@gmail.com>